apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTXpBMk5UWTRPREF3SGhjTk1qUXhNVEF6TVRnd01USXdXaGNOTXpReE1UQXhNVGd3TVRJdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTXpBMk5UWTRPREF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTbFhGMHdZMkZ4WmFRWkJrOTk3MVFSRTZHZFE4blR1cGFSNU5DSVlYOU4KblM4cnlxdFNVcFBhdjhqRjNTaE5ud2tpUi9rQ2pGd3lZcE5pMzk3aG1lTzFvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVU50OGVtbCtJdU1UZGhKRThtejErCnVLTE40ekF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnR0p0azVxRVBYMU03RXdaNU83OThFNURWWkgxS2w0a1YKemx6MW5QUmE5MUFDSUZjWXd4OHE0WFE5Q3JVVU9hamV5YXBldmNaTkt0UkllWXRiUm5KaXp6aUgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      server: https://3.121.206.151:6443
    name: default
contexts:
  - context:
      cluster: default
      user: default
    name: default
current-context: default
kind: Config
preferences: {}
users:
  - name: default
    user:
      client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJR1lJYnVXTWdmaTB3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOek13TmpVMk9EZ3dNQjRYRFRJME1URXdNekU0TURFeU1Gb1hEVEkxTVRFdwpNekU0TURFeU1Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKOHNmNEs3V0xoYzIvNC8KSVhVWm93MWpQeE9hRk44azhBSlR0b1BkMlRKWTBMd3JkWlozZTdwOG83bHNiRWx6OHZ2MkI3OEhzTnpoQ0FWcApzZVUxVHVDalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVFRscHRyb3o0bkVIeEFyTmNFS1QvTjd3enpDakFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlBUkR1TlExNk5XU3NtYmtqbnl5SGlXZk9UUlRucXBWUWtzMGpZaFcwVE00QUlnRHhBY3A4RE93USt1VVFENwo0WXhOcEExd3N4Y3RSU1lrYTR6STdWWTZmUGM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUVhNlEzNjh3Q2hYOEpjeW1sZWN1OHhrSkRwODRUM0NGbms2dGp1N1hmRzFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFbnl4L2dydFl1RnpiL2o4aGRSbWpEV00vRTVvVTN5VHdBbE8yZzkzWk1salF2Q3QxbG5kNwp1bnlqdVd4c1NYUHkrL1lIdndldzNPRUlCV214NVRWTzRBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
