apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http
      port: 9093
      targetPort: 9093
      protocol: TCP
      nodePort: 31001
  selector:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
