apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'node-exporter'
      static_configs:
        - targets:
            - 'node-exporter.monitoring.svc.cluster.local:9100'

    - job_name: 'kube-state-metrics'
      static_configs:
        - targets:
            - 'kube-state-metrics.monitoring.svc.cluster.local:8080'
