apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
      nodePort: 31000
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
