namespace: my-namespace

wordpress:
  image: "wordpress:latest"
  replicaCount: 1
  service:
    port: 80
    nodePort: 32000
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  persistentVolume:
    size: 5Gi

mysql:
  enabled: true
  image: "mysql:5.7"
  rootPassword: "root_password"
  database: "wp_db"
  user: "wp_user"
  password: "wp_password"
  persistentVolume:
    size: 5Gi
