apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-wordpress.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "my-wordpress.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-wordpress.name" . }}
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ include "my-wordpress.fullname" . }}-mysql
            - name: WORDPRESS_DB_USER
              value: {{ .Values.mysql.user }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.mysql.database }}
