apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-wordpress.fullname" . }}-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ include "my-wordpress.name" . }}-mysql
