apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-wordpress.fullname" . }}
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: 80
  selector:
    app: {{ include "my-wordpress.name" . }}
