apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: my-namespace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" 
    metallb.universe.tf/address-pool: "default"
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
