name: WordPress Deployment

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Setup Terraform
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.5

      # Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Initialize Terraform to download providers
      - name: Terraform Init
        run: terraform init

      # Format and Validate Terraform Configuration
      - name: Terraform Format and Validate
        run: |
          terraform fmt -check
          terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Terraform Apply (only for pushes to main)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

  helm-deploy:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Deploy WordPress using Helm
      - name: Deploy WordPress with Helm
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami || true
          helm repo update || true
          kubectl create namespace my-namespace || true
          helm upgrade --install my-wordpress bitnami/wordpress --namespace my-namespace || true
